fix: PyArrow data type mismatch exception
full traceback lmao
```
2026-06-26 00:49:42.086 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "...\Python\Python314\site-packages\streamlit\dataframe_util.py", line 961, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4768, in pyarrow.lib.Table.from_pandas
  File "...\Python\Python314\site-packages\pyarrow\pandas_compat.py", line 651, in dataframe_to_arrays
    arrays = [convert_column(c, f)
              ~~~~~~~~~~~~~~^^^^^^
  File "...\Python\Python314\site-packages\pyarrow\pandas_compat.py", line 639, in convert_column
    raise e
  File "...\Python\Python314\site-packages\pyarrow\pandas_compat.py", line 633, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 390, in pyarrow.lib.array
    result = _ndarray_to_array(values, mask, type, c_from_pandas, safe,
  File "pyarrow/array.pxi", line 91, in pyarrow.lib._ndarray_to_array
    check_status(NdarrayToArrow(pool, values, mask, from_pandas,
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'numpy.int64' object", 'Conversion failed for column value with type object')
```

my bro joseph fixed this issue single handedly which has been bothering me for AGES ❤️❤️❤️ love you bro 🫶🫶🫶

Co-authored-by: Joe <joejo-joestar@users.noreply.github.com>